# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit

language: "en-US"

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

chat:
  auto_reply: true
